services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: app_password
    ports:
      - "5433:5432"   # expose if you want psql from host (optional)
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    build: .
    env_file: .env.docker
    ports:
      - "8000:8000"
    depends_on:
      - db
    # quick & dirty wait; fine for local dev
    command: bash -lc "sleep 3 && alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"
volumes:
  pgdata:
