line-length = 100
target-version = "py312"
fix = true

[lint]
select = ["E", "F", "I", "UP", "B"]
ignore = ["B008", "E402"]

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"