"""create users table

Revision ID: 1e3d16051432
Revises: f53b82919d71
Create Date: 2025-08-30 23:24:13.714017

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "1e3d16051432"
down_revision: str | Sequence[str] | None = "f53b82919d71"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
