name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: appdb
          POSTGRES_USER: appuser
          POSTGRES_PASSWORD: app_password
        ports: ["5432:5432"]
        options: >-
          --health-cmd="pg_isready -U appuser -d appdb"
          --health-interval=5s --health-timeout=5s --health-retries=10
    env:
      DATABASE_URL: postgresql://appuser:app_password@localhost:5432/appdb
      SECRET_KEY: test-secret
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: "60"

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt

      - name: DB migrate
        run: alembic upgrade head

      - name: Pre-commit
        run: pre-commit run --all-files || true  # surfaces issues without failing build

      - name: Pytest
        run: pytest -q
